FROM python:3.7.0
COPY pip.conf pip.conf
ENV PIP_CONFIG_FILE pip.conf
RUN pip install mlflow==1.2.0
RUN pip install psycopg2

EXPOSE 5000

RUN mkdir -p /server
WORKDIR /server
COPY . /server

RUN mkdir /mlflow/

CMD  mlflow server \
    --backend-store-uri postgresql://admin:secret@postgres:5432/mlflow \
    --default-artifact-root /mlflow \
    --port 8889 \
    --host 0.0.0.0
